name: Email Step Demo

on:
  push:
    branches:
      - master  # Or main if that's your default branch

jobs:
  test:
    steps:
      - name: 23f2001697@ds.study.iitm.ac.in
        run: echo "Hello, world!"

